# Word2Vec
## Marissa Burton

### Load in packages

In [1]:
import pandas as pd
import numpy as np
import plotly.express as px

from gensim.corpora import Dictionary
from gensim.models import word2vec

from sklearn.manifold import TSNE as tsne

In [2]:
import warnings
warnings.filterwarnings('ignore', category=FutureWarning)

In [3]:
import gensim
gensim.__version__

'4.4.0'

### Load in CORPUS and set OHCO

In [4]:
OHCO = ['era', 'book_id','chap_num', 'para_num', 'sent_num', 'token_num']
BAG = OHCO[:4]
BAG_2 = OHCO[:3]

In [7]:
CORPUS = pd.read_csv('data/CORPUS.csv').set_index(OHCO).dropna()

/var/folders/k2/xkhh4x_x2999dprlhrz1h_r00000gn/T/ipykernel_76170/458236389.py:1: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  CORPUS = pd.read_csv('data/CORPUS.csv').set_index(OHCO).dropna()

### Convert to Gensim

In [8]:
docs = CORPUS.groupby(BAG).term_str.apply(list).tolist()
docs_2 = CORPUS.groupby(BAG_2).term_str.apply(list).tolist()

In [9]:
for i in range(3):
    print(f"Doc {i}:", docs[i])

Doc 0: ['from', 'geneva']
Doc 1: ['i', 'breathe', 'freely', 'in', 'the', 'neighbourhood', 'of', 'this', 'lake', 'the', 'ground', 'upon', 'which', 'i', 'tread', 'has', 'been', 'subdued', 'from', 'the', 'earliest', 'ages', 'the', 'principal', 'objects', 'which', 'immediately', 'strike', 'my', 'eye', 'bring', 'to', 'my', 'recollection', 'scenes', 'in', 'which', 'man', 'acted', 'the', 'hero', 'and', 'was', 'the', 'chief', 'object', 'of', 'interest', 'not', 'to', 'look', 'back', 'to', 'earlier', 'times', 'of', 'battles', 'and', 'sieges', 'here', 'is', 'the', 'bust', 'of', 'rousseau', 'here', 'is', 'a', 'house', 'with', 'an', 'inscription', 'denoting', 'that', 'the', 'genevan', 'philosopher', 'first', 'drew', 'breath', 'under', 'its', 'roof', 'a', 'little', 'out', 'of', 'the', 'town', 'is', 'ferney', 'the', 'residence', 'of', 'voltaire', 'where', 'that', 'wonderful', 'though', 'certainly', 'in', 'many', 'respects', 'contemptible', 'character', 'received', 'like', 'the', 'hermits', 'of', 'old', 'the', 'visits', 'of', 'pilgrims', 'not', 'only', 'from', 'his', 'own', 'nation', 'but', 'from', 'the', 'farthest', 'boundaries', 'of', 'europe', 'here', 'too', 'is', 'bonnet', 's', 'abode', 'and', 'a', 'few', 'steps', 'beyond', 'the', 'house', 'of', 'that', 'astonishing', 'woman', 'madame', 'de', 'stael', 'perhaps', 'the', 'first', 'of', 'her', 'sex', 'who', 'has', 'really', 'proved', 'its', 'often', 'claimed', 'equality', 'with', 'the', 'nobler', 'man', 'we', 'have', 'before', 'had', 'women', 'who', 'have', 'written', 'interesting', 'novels', 'and', 'poems', 'in', 'which', 'their', 'tact', 'at', 'observing', 'drawing', 'room', 'characters', 'has', 'availed', 'them', 'but', 'never', 'since', 'the', 'days', 'of', 'heloise', 'have', 'those', 'faculties', 'which', 'are', 'peculiar', 'to', 'man', 'been', 'developed', 'as', 'the', 'possible', 'inheritance', 'of', 'woman', 'though', 'even', 'here', 'as', 'in', 'the', 'case', 'of', 'heloise', 'our', 'sex', 'have', 'not', 'been', 'backward', 'in', 'alledging', 'the', 'existence', 'of', 'an', 'abeilard', 'in', 'the', 'person', 'of', 'm', 'schlegel', 'as', 'the', 'inspirer', 'of', 'her', 'works', 'but', 'to', 'proceed', 'upon', 'the', 'same', 'side', 'of', 'the', 'lake', 'gibbon', 'bonnivard', 'bradshaw', 'and', 'others', 'mark', 'as', 'it', 'were', 'the', 'stages', 'for', 'our', 'progress', 'whilst', 'upon', 'the', 'other', 'side', 'there', 'is', 'one', 'house', 'built', 'by', 'diodati', 'the', 'friend', 'of', 'milton', 'which', 'has', 'contained', 'within', 'its', 'walls', 'for', 'several', 'months', 'that', 'poet', 'whom', 'we', 'have', 'so', 'often', 'read', 'together', 'and', 'who', 'if', 'human', 'passions', 'remain', 'the', 'same', 'and', 'human', 'feelings', 'like', 'chords', 'on', 'being', 'swept', 'by', 'nature', 's', 'impulses', 'shall', 'vibrate', 'as', 'before', 'will', 'be', 'placed', 'by', 'posterity', 'in', 'the', 'first', 'rank', 'of', 'our', 'english', 'poets', 'you', 'must', 'have', 'heard', 'or', 'the', 'third', 'canto', 'of', 'childe', 'harold', 'will', 'have', 'informed', 'you', 'that', 'lord', 'byron', 'resided', 'many', 'months', 'in', 'this', 'neighbourhood', 'i', 'went', 'with', 'some', 'friends', 'a', 'few', 'days', 'ago', 'after', 'having', 'seen', 'ferney', 'to', 'view', 'this', 'mansion', 'i', 'trod', 'the', 'floors', 'with', 'the', 'same', 'feelings', 'of', 'awe', 'and', 'respect', 'as', 'we', 'did', 'together', 'those', 'of', 'shakespeare', 's', 'dwelling', 'at', 'stratford', 'i', 'sat', 'down', 'in', 'a', 'chair', 'of', 'the', 'saloon', 'and', 'satisfied', 'myself', 'that', 'i', 'was', 'resting', 'on', 'what', 'he', 'had', 'made', 'his', 'constant', 'seat', 'i', 'found', 'a', 'servant', 'there', 'who', 'had', 'lived', 'with', 'him', 'she', 'however', 'gave', 'me', 'but', 'little', 'information', 'she', 'pointed', 'out', 'his', 'bed', 'chamber', 'upon', 'the', 'same', 'level', 'as', 'the', 'saloon', 'and', 'dining', 'room', 'and', 'informed', 'me', 'that', 'he', 'retired', 'to', 'rest', 'at', 'three', 'got', 'up', 'at', 'two', 'and', 'employed', 'himself', 'a', 'long', 'time', 'over', 'his', 'toilette', 'that', 'he', 'never', 'went', 'to', 'sleep', 'without', 'a', 'pair', 'of', 'pistols', 'and', 'a', 'dagger', 'by', 'his', 'side', 'and', 'that', 'he', 'never', 'ate', 'animal', 'food', 'he', 'apparently', 'spent', 'some', 'part', 'of', 'every', 'day', 'upon', 'the', 'lake', 'in', 'an', 'english', 'boat', 'there', 'is', 'a', 'balcony', 'from', 'the', 'saloon', 'which', 'looks', 'upon', 'the', 'lake', 'and', 'the', 'mountain', 'jura', 'and', 'i', 'imagine', 'that', 'it', 'must', 'have', 'been', 'hence', 'he', 'contemplated', 'the', 'storm', 'so', 'magnificently', 'described', 'in', 'the', 'third', 'canto', 'for', 'you', 'have', 'from', 'here', 'a', 'most', 'extensive', 'view', 'of', 'all', 'the', 'points', 'he', 'has', 'therein', 'depicted', 'i', 'can', 'fancy', 'him', 'like', 'the', 'scathed', 'pine', 'whilst', 'all', 'around', 'was', 'sunk', 'to', 'repose', 'still', 'waking', 'to', 'observe', 'what', 'gave', 'but', 'a', 'weak', 'image', 'of', 'the', 'storms', 'which', 'had', 'desolated', 'his', 'own', 'breast']
Doc 2: ['the', 'sky', 'is', 'changed', 'and', 'such', 'a', 'change', 'oh', 'night', 'and', 'storm', 'and', 'darkness', 'ye', 'are', 'wond', 'rous', 'strong', 'yet', 'lovely', 'in', 'your', 'strength', 'as', 'is', 'the', 'light', 'of', 'a', 'dark', 'eye', 'in', 'woman', 'far', 'along', 'from', 'peak', 'to', 'peak', 'the', 'rattling', 'crags', 'among', 'leaps', 'the', 'lire', 'thunder', 'not', 'from', 'one', 'lone', 'cloud', 'but', 'every', 'mountain', 'now', 'hath', 'found', 'a', 'tongue', 'and', 'jura', 'answers', 'thro', 'her', 'misty', 'shroud', 'back', 'to', 'the', 'joyous', 'alps', 'who', 'call', 'to', 'her', 'aloud']

### Extract a dictionary (vocabulary)

In [10]:
dictionary = Dictionary(docs)
dictionary_2 = Dictionary(docs_2)

### Generate word embeddings

In [11]:
w2v_params = dict(
    window = 2,
    vector_size = 200,
    min_count = 50,
    workers = 4
)

In [12]:
model = word2vec.Word2Vec(docs, **w2v_params)
model.wv.vectors

array([[ 0.20789103,  0.073307  , -0.05688835, ..., -0.14293431,
        -0.30907497,  0.27155742],
       [ 0.1461972 ,  0.01817968, -0.16409086, ..., -0.14435434,
        -0.1101207 ,  0.02718773],
       [-0.30516538,  0.2099334 , -0.1543494 , ...,  0.19988805,
         0.11896015, -0.31271863],
       ...,
       [ 0.074418  , -0.02302828,  0.00135719, ..., -0.03141534,
        -0.01106009,  0.05559859],
       [ 0.14849383, -0.00316548, -0.04641817, ..., -0.07115831,
        -0.04442162,  0.03549761],
       [ 0.1281107 , -0.02081932,  0.00407336, ..., -0.05596033,
        -0.04566684,  0.04588293]], dtype=float32)

In [13]:
model_2 = word2vec.Word2Vec(docs_2, **w2v_params)
model_2.wv.vectors

array([[ 0.03525376, -0.00882927, -0.02033675, ..., -0.04630952,
        -0.21349847,  0.24068268],
       [ 0.09862114,  0.05530657, -0.17478901, ..., -0.20610513,
        -0.12666439, -0.06549924],
       [-0.08918461,  0.023248  , -0.21514124, ...,  0.10912005,
         0.23183036, -0.25062302],
       ...,
       [ 0.12299772, -0.06218877, -0.0451649 , ..., -0.0723095 ,
         0.01890636,  0.00795673],
       [ 0.18415125, -0.03271288, -0.049637  , ..., -0.11168595,
        -0.00843517, -0.02587374],
       [ 0.10705177, -0.04779815, -0.04620575, ..., -0.06750731,
        -0.00536152,  0.00062602]], dtype=float32)

### Convert model to dataframe

In [14]:
WV = pd.DataFrame(model.wv.vectors, index=model.wv.index_to_key)
WV.index.name = 'term_str'
WV

,0,1,2,3,4,5,6,7,8,9,...,190,191,192,193,194,195,196,197,198,199
term_str,,,,,,,,,,,,,,,,,,,,,
the,0.207891,0.073307,-0.056888,0.170464,-0.321607,-0.146827,0.366681,0.132336,-0.124543,-0.118886,...,0.418642,0.125774,-0.265077,-0.321873,-0.173305,0.278295,0.182470,-0.142934,-0.309075,0.271557
and,0.146197,0.018180,-0.164091,0.104806,0.037719,0.100762,-0.011080,0.199058,-0.016731,0.035298,...,0.087995,0.071127,-0.345349,-0.022476,0.018551,0.168085,-0.002729,-0.144354,-0.110121,0.027188
to,-0.305165,0.209933,-0.154349,0.006134,-0.008734,0.128567,0.359347,0.230170,-0.224106,0.004574,...,0.032211,0.303995,-0.279411,-0.012514,0.079760,0.197511,-0.128295,0.199888,0.118960,-0.312719
of,0.138846,0.082657,-0.241587,0.322588,0.043232,0.169656,0.152458,-0.130490,0.078777,-0.414501,...,0.206638,-0.042974,-0.198054,0.309495,-0.076514,-0.051158,-0.278881,0.342207,0.013099,-0.045057
i,-0.350117,-0.316765,-0.019812,-0.072382,0.469485,-0.276700,0.182811,0.574645,-0.000770,0.280218,...,-0.559031,0.229957,0.000083,-0.080257,0.171509,-0.002143,-0.433705,0.226825,0.105488,0.255758
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
fears,0.044143,-0.047774,-0.029161,-0.022860,0.051093,-0.049429,-0.013267,0.143277,0.032897,0.126346,...,0.133563,-0.001737,-0.088632,-0.039011,-0.006001,0.107229,0.101561,-0.051774,-0.010253,0.033620
run,0.062779,-0.056580,-0.000692,-0.015196,0.101165,-0.117777,-0.005327,0.185490,-0.017626,0.080814,...,0.148116,-0.009415,-0.097036,-0.086189,-0.065039,0.105909,0.086301,-0.050596,-0.006017,0.023419
rooms,0.074418,-0.023028,0.001357,-0.003046,0.058706,-0.091943,0.037087,0.151194,-0.005431,0.112593,...,0.135080,0.021732,-0.052098,-0.022009,-0.037111,0.056329,0.057839,-0.031415,-0.011060,0.055599
breast,0.148494,-0.003165,-0.046418,0.022110,-0.001408,0.005023,-0.032099,0.100536,0.046073,0.111293,...,0.212521,-0.034278,-0.168558,-0.033209,-0.019558,0.147161,0.144194,-0.071158,-0.044422,0.035498
town,0.128111,-0.020819,0.004073,0.011622,0.044438,-0.111133,0.002836,0.144829,-0.047060,0.076771,...,0.214372,0.007960,-0.105102,-0.086299,-0.087266,0.108245,0.110525,-0.055960,-0.045667,0.045883

In [15]:
WV_2 = pd.DataFrame(model_2.wv.vectors, index=model_2.wv.index_to_key)
WV_2.index.name = 'term_str'
WV_2

,0,1,2,3,4,5,6,7,8,9,...,190,191,192,193,194,195,196,197,198,199
term_str,,,,,,,,,,,,,,,,,,,,,
the,0.035254,-0.008829,-0.020337,0.050299,-0.284595,-0.347766,0.394396,0.281864,-0.354059,-0.268702,...,0.205337,0.142711,-0.338322,-0.378540,-0.337215,-0.001061,0.225873,-0.046310,-0.213498,0.240683
and,0.098621,0.055307,-0.174789,0.038385,0.170141,-0.063934,0.157567,0.362375,-0.033346,0.093600,...,-0.007372,0.069813,-0.288896,-0.061516,0.010557,0.048273,0.081232,-0.206105,-0.126664,-0.065499
to,-0.089185,0.023248,-0.215141,0.064655,0.002569,0.097702,0.296927,0.362867,-0.070125,0.273453,...,0.045532,0.295960,-0.192590,-0.140252,0.118266,-0.032584,0.138562,0.109120,0.231830,-0.250623
of,0.400991,-0.063173,-0.272409,0.079442,-0.109248,-0.056892,0.419801,0.228798,-0.067278,0.083176,...,0.209614,-0.010674,-0.231251,0.280249,0.043752,-0.181470,-0.122726,0.115101,-0.069532,-0.055980
i,-0.296429,-0.040242,-0.096854,-0.069745,0.294333,-0.280622,0.116218,0.622492,-0.154130,0.271742,...,-0.281261,0.209808,-0.094340,-0.234581,0.236375,-0.075020,-0.222253,0.204163,0.063947,0.108980
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
fears,0.108965,-0.045491,-0.042633,-0.034173,0.086054,-0.066019,0.053227,0.186639,-0.000802,0.116299,...,0.142422,0.003686,-0.102175,-0.009653,0.006070,0.080163,0.086029,-0.053006,0.028368,-0.001570
run,0.062978,-0.050722,-0.022357,-0.039515,0.122572,-0.140412,-0.004172,0.230388,-0.060670,0.077292,...,0.184005,0.015108,-0.117668,-0.060831,-0.046365,0.098266,0.076855,-0.040674,-0.021239,-0.005974
rooms,0.122998,-0.062189,-0.045165,-0.018722,0.092926,-0.123254,0.054520,0.203394,-0.017362,0.112089,...,0.187238,0.002999,-0.121906,-0.028279,-0.032094,0.072748,0.072876,-0.072310,0.018906,0.007957
breast,0.184151,-0.032713,-0.049637,-0.052467,0.102809,-0.054586,0.038333,0.265405,0.011044,0.163625,...,0.156701,-0.029747,-0.133437,0.004319,0.022042,0.122421,0.127167,-0.111686,-0.008435,-0.025874
town,0.107052,-0.047798,-0.046206,-0.040591,0.073474,-0.125150,0.033943,0.208810,-0.040884,0.082450,...,0.210326,0.000517,-0.124232,-0.046887,-0.052475,0.081713,0.050871,-0.067507,-0.005362,0.000626

### tSNE

In [16]:
PP = 40

tsne_engine = tsne(
    perplexity=PP, 
    n_components=2, 
    init='pca', 
    max_iter=2500, 
    random_state=23
)
TSNE = pd.DataFrame(
    tsne_engine.fit_transform(WV), 
    columns=['x','y'], 
    index=WV.index)
TSNE

                  x          y
term_str
the       20.650381 -14.130098
and       26.994452 -10.521393
to       -33.165535   7.418328
of        33.679546 -12.148816
i        -28.477543  -7.679677
...             ...        ...
fears     -2.471569   2.041616
run        1.706006  -4.875447
rooms      6.088829  -0.424670
breast    24.532169   3.753169
town      14.950726  -1.994171

[866 rows x 2 columns]

In [17]:
tsne_engine = tsne(
    perplexity=PP, 
    n_components=2, 
    init='pca', 
    max_iter=2500, 
    random_state=23
)
TSNE_2 = pd.DataFrame(
    tsne_engine.fit_transform(WV_2), 
    columns=['x','y'], 
    index=WV_2.index)
TSNE_2

                  x          y
term_str
the      -33.693878   7.942669
and      -20.182859  -9.198045
to       -21.246809 -16.745789
of       -20.452936 -14.694837
i         33.286041   3.677902
...             ...        ...
fears     -4.396294  -2.806726
run        1.201893   3.507445
rooms    -10.160310   1.686089
breast   -20.818678  -5.776061
town     -11.269322   3.275665

[866 rows x 2 columns]

In [18]:
px.scatter(TSNE.reset_index(), 'x', 'y', 
        text='term_str', 
        hover_name='term_str',  
        height=1000,
        width=1200)\
    .update_traces(
        mode='markers+text', 
        textfont=dict(color='black', size=14, family='Arial'),
        textposition='top center')

In [19]:
px.scatter(TSNE_2.reset_index(), 'x', 'y', 
        text='term_str', 
        hover_name='term_str',  
        height=1000,
        width=1200)\
    .update_traces(
        mode='markers+text', 
        textfont=dict(color='black', size=14, family='Arial'),
        textposition='top center')

### Export WV table

In [21]:
WV.to_csv('data/VOCAB_W2V.csv')