# Word2Vec
## Marissa Burton

### Load in packages

In [48]:
import pandas as pd
import numpy as np
import plotly.express as px

from gensim.corpora import Dictionary
from gensim.models import word2vec

from sklearn.manifold import TSNE as tsne

In [49]:
import warnings
warnings.filterwarnings('ignore', category=FutureWarning)

In [50]:
import gensim
gensim.__version__

'4.4.0'

### Load in CORPUS and set OHCO

In [51]:
OHCO = ['era', 'book_id','chap_num', 'para_num', 'sent_num', 'token_num']
BAG = OHCO[:4]

In [52]:
CORPUS = pd.read_csv('../data/CORPUS.csv').set_index(OHCO).dropna()

/var/folders/k2/xkhh4x_x2999dprlhrz1h_r00000gn/T/ipykernel_15518/2366809384.py:1: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  CORPUS = pd.read_csv('../data/CORPUS.csv').set_index(OHCO).dropna()

### Convert to Gensim

In [53]:
docs = CORPUS.groupby(BAG).term_str.apply(list).tolist()

In [54]:
for i in range(3):
    print(f"Doc {i}:", docs[i])

Doc 0: ['from', 'geneva']
Doc 1: ['i', 'breathe', 'freely', 'in', 'the', 'neighbourhood', 'of', 'this', 'lake', 'the', 'ground', 'upon', 'which', 'i', 'tread', 'has', 'been', 'subdued', 'from', 'the', 'earliest', 'ages', 'the', 'principal', 'objects', 'which', 'immediately', 'strike', 'my', 'eye', 'bring', 'to', 'my', 'recollection', 'scenes', 'in', 'which', 'man', 'acted', 'the', 'hero', 'and', 'was', 'the', 'chief', 'object', 'of', 'interest', 'not', 'to', 'look', 'back', 'to', 'earlier', 'times', 'of', 'battles', 'and', 'sieges', 'here', 'is', 'the', 'bust', 'of', 'rousseau', 'here', 'is', 'a', 'house', 'with', 'an', 'inscription', 'denoting', 'that', 'the', 'genevan', 'philosopher', 'first', 'drew', 'breath', 'under', 'its', 'roof', 'a', 'little', 'out', 'of', 'the', 'town', 'is', 'ferney', 'the', 'residence', 'of', 'voltaire', 'where', 'that', 'wonderful', 'though', 'certainly', 'in', 'many', 'respects', 'contemptible', 'character', 'received', 'like', 'the', 'hermits', 'of', 'old', 'the', 'visits', 'of', 'pilgrims', 'not', 'only', 'from', 'his', 'own', 'nation', 'but', 'from', 'the', 'farthest', 'boundaries', 'of', 'europe', 'here', 'too', 'is', 'bonnet', 's', 'abode', 'and', 'a', 'few', 'steps', 'beyond', 'the', 'house', 'of', 'that', 'astonishing', 'woman', 'madame', 'de', 'stael', 'perhaps', 'the', 'first', 'of', 'her', 'sex', 'who', 'has', 'really', 'proved', 'its', 'often', 'claimed', 'equality', 'with', 'the', 'nobler', 'man', 'we', 'have', 'before', 'had', 'women', 'who', 'have', 'written', 'interesting', 'novels', 'and', 'poems', 'in', 'which', 'their', 'tact', 'at', 'observing', 'drawing', 'room', 'characters', 'has', 'availed', 'them', 'but', 'never', 'since', 'the', 'days', 'of', 'heloise', 'have', 'those', 'faculties', 'which', 'are', 'peculiar', 'to', 'man', 'been', 'developed', 'as', 'the', 'possible', 'inheritance', 'of', 'woman', 'though', 'even', 'here', 'as', 'in', 'the', 'case', 'of', 'heloise', 'our', 'sex', 'have', 'not', 'been', 'backward', 'in', 'alledging', 'the', 'existence', 'of', 'an', 'abeilard', 'in', 'the', 'person', 'of', 'm', 'schlegel', 'as', 'the', 'inspirer', 'of', 'her', 'works', 'but', 'to', 'proceed', 'upon', 'the', 'same', 'side', 'of', 'the', 'lake', 'gibbon', 'bonnivard', 'bradshaw', 'and', 'others', 'mark', 'as', 'it', 'were', 'the', 'stages', 'for', 'our', 'progress', 'whilst', 'upon', 'the', 'other', 'side', 'there', 'is', 'one', 'house', 'built', 'by', 'diodati', 'the', 'friend', 'of', 'milton', 'which', 'has', 'contained', 'within', 'its', 'walls', 'for', 'several', 'months', 'that', 'poet', 'whom', 'we', 'have', 'so', 'often', 'read', 'together', 'and', 'who', 'if', 'human', 'passions', 'remain', 'the', 'same', 'and', 'human', 'feelings', 'like', 'chords', 'on', 'being', 'swept', 'by', 'nature', 's', 'impulses', 'shall', 'vibrate', 'as', 'before', 'will', 'be', 'placed', 'by', 'posterity', 'in', 'the', 'first', 'rank', 'of', 'our', 'english', 'poets', 'you', 'must', 'have', 'heard', 'or', 'the', 'third', 'canto', 'of', 'childe', 'harold', 'will', 'have', 'informed', 'you', 'that', 'lord', 'byron', 'resided', 'many', 'months', 'in', 'this', 'neighbourhood', 'i', 'went', 'with', 'some', 'friends', 'a', 'few', 'days', 'ago', 'after', 'having', 'seen', 'ferney', 'to', 'view', 'this', 'mansion', 'i', 'trod', 'the', 'floors', 'with', 'the', 'same', 'feelings', 'of', 'awe', 'and', 'respect', 'as', 'we', 'did', 'together', 'those', 'of', 'shakespeare', 's', 'dwelling', 'at', 'stratford', 'i', 'sat', 'down', 'in', 'a', 'chair', 'of', 'the', 'saloon', 'and', 'satisfied', 'myself', 'that', 'i', 'was', 'resting', 'on', 'what', 'he', 'had', 'made', 'his', 'constant', 'seat', 'i', 'found', 'a', 'servant', 'there', 'who', 'had', 'lived', 'with', 'him', 'she', 'however', 'gave', 'me', 'but', 'little', 'information', 'she', 'pointed', 'out', 'his', 'bed', 'chamber', 'upon', 'the', 'same', 'level', 'as', 'the', 'saloon', 'and', 'dining', 'room', 'and', 'informed', 'me', 'that', 'he', 'retired', 'to', 'rest', 'at', 'three', 'got', 'up', 'at', 'two', 'and', 'employed', 'himself', 'a', 'long', 'time', 'over', 'his', 'toilette', 'that', 'he', 'never', 'went', 'to', 'sleep', 'without', 'a', 'pair', 'of', 'pistols', 'and', 'a', 'dagger', 'by', 'his', 'side', 'and', 'that', 'he', 'never', 'ate', 'animal', 'food', 'he', 'apparently', 'spent', 'some', 'part', 'of', 'every', 'day', 'upon', 'the', 'lake', 'in', 'an', 'english', 'boat', 'there', 'is', 'a', 'balcony', 'from', 'the', 'saloon', 'which', 'looks', 'upon', 'the', 'lake', 'and', 'the', 'mountain', 'jura', 'and', 'i', 'imagine', 'that', 'it', 'must', 'have', 'been', 'hence', 'he', 'contemplated', 'the', 'storm', 'so', 'magnificently', 'described', 'in', 'the', 'third', 'canto', 'for', 'you', 'have', 'from', 'here', 'a', 'most', 'extensive', 'view', 'of', 'all', 'the', 'points', 'he', 'has', 'therein', 'depicted', 'i', 'can', 'fancy', 'him', 'like', 'the', 'scathed', 'pine', 'whilst', 'all', 'around', 'was', 'sunk', 'to', 'repose', 'still', 'waking', 'to', 'observe', 'what', 'gave', 'but', 'a', 'weak', 'image', 'of', 'the', 'storms', 'which', 'had', 'desolated', 'his', 'own', 'breast']
Doc 2: ['the', 'sky', 'is', 'changed', 'and', 'such', 'a', 'change', 'oh', 'night', 'and', 'storm', 'and', 'darkness', 'ye', 'are', 'wond', 'rous', 'strong', 'yet', 'lovely', 'in', 'your', 'strength', 'as', 'is', 'the', 'light', 'of', 'a', 'dark', 'eye', 'in', 'woman', 'far', 'along', 'from', 'peak', 'to', 'peak', 'the', 'rattling', 'crags', 'among', 'leaps', 'the', 'lire', 'thunder', 'not', 'from', 'one', 'lone', 'cloud', 'but', 'every', 'mountain', 'now', 'hath', 'found', 'a', 'tongue', 'and', 'jura', 'answers', 'thro', 'her', 'misty', 'shroud', 'back', 'to', 'the', 'joyous', 'alps', 'who', 'call', 'to', 'her', 'aloud']

### Extract a dictionary (vocabulary)

In [55]:
dictionary = Dictionary(docs)

### Generate word embeddings

In [ ]:
w2v_params = dict(
    window = 2,
    vector_size = 200,
    min_count = 50,
    workers = 4
)

In [57]:
model = word2vec.Word2Vec(docs, **w2v_params)
model.wv.vectors

array([[ 0.15946673, -0.12104677, -0.03304542, ..., -0.03173968,
        -0.28700763,  0.5099848 ],
       [ 0.3217468 , -0.10444931, -0.18079406, ..., -0.1286339 ,
        -0.20017684,  0.09814028],
       [-0.26586607,  0.03801363, -0.16106232, ...,  0.1767632 ,
         0.37346157, -0.18408863],
       ...,
       [ 0.14654069, -0.04012989, -0.0242012 , ..., -0.03075582,
        -0.00247899,  0.04139617],
       [ 0.2019244 , -0.01443102, -0.06466904, ..., -0.06333344,
        -0.04753784,  0.05477596],
       [ 0.1608748 , -0.04229676, -0.02335073, ..., -0.05086829,
        -0.0596172 ,  0.02152108]], dtype=float32)

### Convert model to dataframe

In [58]:
WV = pd.DataFrame(model.wv.vectors, index=model.wv.index_to_key)
WV.index.name = 'term_str'
WV

,0,1,2,3,4,5,6,7,8,9,...,190,191,192,193,194,195,196,197,198,199
term_str,,,,,,,,,,,,,,,,,,,,,
the,0.159467,-0.121047,-0.033045,0.230170,-0.306695,-0.221609,0.585032,0.138959,-0.058379,-0.279911,...,0.327989,0.121755,-0.270754,-0.087433,-0.380395,0.105490,0.206342,-0.031740,-0.287008,0.509985
and,0.321747,-0.104449,-0.180794,0.032111,0.147210,0.093945,0.123676,0.239658,-0.076529,0.137005,...,-0.058623,0.001879,-0.166476,0.083163,0.078678,0.143908,0.113604,-0.128634,-0.200177,0.098140
to,-0.265866,0.038014,-0.161062,-0.034656,-0.111197,0.129169,0.321080,0.104018,-0.210801,0.266206,...,-0.051850,0.177007,-0.202644,-0.054847,0.146479,0.209821,-0.023258,0.176763,0.373462,-0.184089
of,0.201662,-0.024038,-0.206726,0.282123,0.110971,0.182336,0.096969,-0.047936,-0.086077,-0.238652,...,0.053021,0.093991,-0.199780,0.377505,-0.162923,-0.121486,-0.370740,0.389074,0.000453,0.027713
i,-0.709911,0.042032,0.096736,0.009319,0.376930,0.041196,0.222386,0.076427,0.090422,0.205817,...,-0.403900,0.024594,0.189183,-0.268094,0.246409,-0.066450,-0.425958,0.241244,0.406070,0.189265
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
fears,0.111691,-0.040272,-0.057453,-0.025125,0.044949,-0.067201,-0.003790,0.196138,0.067596,0.172695,...,0.152667,0.005837,-0.146677,-0.021877,-0.006219,0.130635,0.115413,-0.058234,0.043701,0.047848
run,0.046218,-0.053493,0.001320,-0.044818,0.120451,-0.136883,0.000918,0.187955,-0.020343,0.095395,...,0.158028,0.009708,-0.122945,-0.099409,-0.085657,0.125377,0.073666,-0.058735,-0.021429,0.017699
rooms,0.146541,-0.040130,-0.024201,0.000177,0.084763,-0.106224,0.016712,0.209570,-0.002318,0.115092,...,0.198342,0.050824,-0.114299,-0.024227,-0.060524,0.091069,0.060511,-0.030756,-0.002479,0.041396
breast,0.201924,-0.014431,-0.064669,0.012846,0.037847,-0.057703,-0.000933,0.263053,0.047055,0.142213,...,0.240660,0.008290,-0.222755,-0.042923,-0.033402,0.179279,0.212841,-0.063333,-0.047538,0.054776
town,0.160875,-0.042297,-0.023351,-0.015669,0.079315,-0.138543,0.009833,0.215723,-0.032049,0.050315,...,0.260129,0.056052,-0.146534,-0.072002,-0.127446,0.128002,0.095776,-0.050868,-0.059617,0.021521

### tSNE

In [59]:
PP = 40

tsne_engine = tsne(
    perplexity=PP, 
    n_components=2, 
    init='pca', 
    max_iter=2500, 
    random_state=23
)
TSNE = pd.DataFrame(
    tsne_engine.fit_transform(WV), 
    columns=['x','y'], 
    index=WV.index)
TSNE

                  x          y
term_str
the      -16.144035 -20.424475
and      -25.622681  -6.058627
to        36.686821   1.691272
of       -31.459562 -13.533465
i         32.722343   5.739347
...             ...        ...
fears      3.122672  -0.687447
run       10.019053   2.009390
rooms     -6.732534  -7.742632
breast   -21.540443  -2.362288
town     -13.278634  -6.193688

[866 rows x 2 columns]

In [60]:
px.scatter(TSNE.reset_index(), 'x', 'y', 
        text='term_str', 
        hover_name='term_str',  
        height=1000,
        width=1200)\
    .update_traces(
        mode='markers+text', 
        textfont=dict(color='black', size=14, family='Arial'),
        textposition='top center')

### Export WV table

In [63]:
WV.to_csv('../data/VOCAB_W2V.csv')